export type Building = "Zentrum" | "Irchel" | "Oerlikon";

export type SeatingStyle = "Theatre" | "Classroom" | "Boardroom" | "Standing" | "Flexible";

export interface Accessibility {
  /** Step-free path from outside the building to the room (Uniability: "Stufenloser Weg"). */
  wheelchairAccessible: boolean;
  /** Induction hearing loop (Uniability: "Induktive Höranlage"). */
  hearingLoop: boolean;
  /** Whether there are steps inside the room itself, even if the path in is step-free. */
  stepsInsideRoom?: boolean;
  doorWidthCm?: number;
  reservedWheelchairSeats?: number;
  notes?: string;
}

export interface Amenities {
  seatingStyle: SeatingStyle[];
  projector: boolean;
  whiteboard: boolean;
  videoConferencing: boolean;
  naturalLight: boolean;
}

export interface Room {
  id: string;
  name: string;
  shortCode: string;
  building: Building;
  address: string;
  capacity: number;
  description: string;
  features: string[];
  image: string;
  imageAlt: string;
  imageCredit?: string;
  accessibility: Accessibility;
  /** Raw question/answer pairs scraped from Uniability, shown as a detailed report. */
  accessibilityDetails?: Record<string, string>;
  amenities: Amenities;
  sourceUrl: string;
  /** Uniability room page, when one exists for this room. */
  uniabilityUrl?: string;
  /** 360°/3D room viewer iframe URLs from del.uzh.ch (front/back view, etc). */
  visual3dUrls: string[];
  availableNow: boolean;
  nextAvailableSlot: string;
}

export const rooms: Room[] = [
  {
    id: "hah-e-03",
    name: "HAH-E-03 Hörsaal",
    shortCode: "HAH-E-03",
    building: "Zentrum",
    address: "Häldeliweg 4, 8044 Zürich",
    capacity: 442,
    description: "A 442-seat lecture hall in Häldeliweg (HAH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/hah-e-03/1.jpg",
    imageAlt: "HAH-E-03 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 95.4,
      reservedWheelchairSeats: 2,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "95.4",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Anzahl Sitzplätze": "442",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72.8",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "102",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "28",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "2",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-03.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-03/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms//HAH-E-03/HAH-E-03_vorne/app-files", "https://del.uzh.ch/static/rooms/HAH-E-03/HAH-E-03_hinten/app-files"],
    availableNow: true,
    nextAvailableSlot: "16:00",
  },
  {
    id: "hah-e-10",
    name: "HAH-E-10 Seminarraum",
    shortCode: "HAH-E-10",
    building: "Zentrum",
    address: "Häldeliweg 4, 8044 Zürich",
    capacity: 36,
    description: "A seminar room in Häldeliweg (HAH) on the UZH Zentrum campus, suited to smaller classes, workshops and committee meetings.",
    features: ["Wheelchair accessible", "Flexible seating"],
    image: "/images/rooms/hah-e-10/1.jpg",
    imageAlt: "HAH-E-10 Seminarraum: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: false,
      doorWidthCm: 102,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "102",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Nein",
      "Trittkantenmarkierungen innerhalb vorhanden": "",
      "Anzahl Sitzplätze": "36",
      "Bestuhlung fix": "Nein",
      "Standorte der von Studierenden benutzbaren Stromanschlüsse": "keine vorhanden",
      "Verstärker-Anlage vorhanden": "Nein",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "67.2",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "65",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "55",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Classroom", "Boardroom"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-10.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-10/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/HAH-E-10/app-files", "https://del.uzh.ch/static/rooms/HAH-E-10/app-files/"],
    availableNow: false,
    nextAvailableSlot: "09:00 tomorrow",
  },
  {
    id: "hah-e-11",
    name: "HAH-E-11 Hörsaal",
    shortCode: "HAH-E-11",
    building: "Zentrum",
    address: "Häldeliweg 4, 8044 Zürich",
    capacity: 285,
    description: "A 285-seat lecture hall in Häldeliweg (HAH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/hah-e-11/1.jpg",
    imageAlt: "HAH-E-11 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 92,
      reservedWheelchairSeats: 2,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "92",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Anzahl Sitzplätze": "285",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "73.1",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "58.9",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "16",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "2",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-11.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-11/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms//HAH-E-03/HAH-E-03_vorne/app-files", "https://del.uzh.ch/static/rooms/Hah-E-11/HAH-E-11_vorne/app-files", "https://del.uzh.ch/static/rooms/Hah-E-11/HAH-E-11_hinten/app-files"],
    availableNow: true,
    nextAvailableSlot: "11:00",
  },
  {
    id: "koh-b-10",
    name: "KOH-B-10 Hörsaal",
    shortCode: "KOH-B-10",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 463,
    description: "A 463-seat lecture hall in the Hauptgebäude (KOH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/koh-b-10/1.jpg",
    imageAlt: "KOH-B-10 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 115,
      reservedWheelchairSeats: 2,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "115",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Ja",
      "Anzahl Sitzplätze": "463",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "74",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "66",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "34",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "2",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOH-B-10.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/KOH/rooms/B-10/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KOH-B-10/KOH-B-10vorne/app-files/", "https://del.uzh.ch/static/rooms/KOH-B-10/KOH-B-10hinten/app-files/"],
    availableNow: false,
    nextAvailableSlot: "13:00 tomorrow",
  },
  {
    id: "kol-lichthof",
    name: "KOL Lichthof",
    shortCode: "KOL Lichthof",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 500,
    description: "A glass-roofed atrium in the Hauptgebäude (KOL) — a landmark space for receptions, exhibitions and large gatherings.",
    features: ["Wheelchair accessible", "Historical architecture", "Large event space"],
    image: "/images/rooms/kol-lichthof.jpg",
    imageAlt: "The historic glass-roofed Lichthof atrium at UZH's main building",
    imageCredit: "Campus Culture UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Standing", "Flexible"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-lichthof.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Lichthof-UZH-Zentrum/LichthofNord/app-files/", "https://del.uzh.ch/static/rooms/Lichthof-UZH-Zentrum/LichthofSued/app-files/"],
    availableNow: true,
    nextAvailableSlot: "10:00",
  },
  {
    id: "kol-f-101",
    name: "KOL-F-101 Hörsaal",
    shortCode: "KOL-F-101",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 213,
    description: "A 213-seat lecture hall in the Hauptgebäude (KOL) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/kol-f-101/1.jpg",
    imageAlt: "KOL-F-101 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 102,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Ja",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "102",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Beschreibung der ebenerdigen Sitzreihen": "Die ersten vier Reihen sind ebenerdig.",
      "Anzahl Sitzplätze": "213",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "73",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "56",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "32",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "2",
      "Diese Tische sind verschiebbar": "Ja",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "84",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "45",
      "Stromanschluss bei diesen Tischen vorhanden": "Ja",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-F-101.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/F-101/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_hinten/app-files/", "https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_vornemitte/app-files/", "https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_vornelinks/app-files/"],
    availableNow: true,
    nextAvailableSlot: "15:00",
  },
  {
    id: "kol-g-201",
    name: "KOL-G-201 Aula",
    shortCode: "KOL-G-201",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 280,
    description: "UZH's ceremonial Aula in the Hauptgebäude (KOL) — a stately hall traditionally used for graduations and formal university ceremonies.",
    features: ["Wheelchair accessible", "Hearing loop", "Grand acoustics", "Historic hall"],
    image: "/images/rooms/kol-g-201/1.jpg",
    imageAlt: "KOL-G-201 Aula: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: false,
      doorWidthCm: 120,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Ja",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "120",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Nein",
      "Trittkantenmarkierungen innerhalb vorhanden": "",
      "Beschreibung der ebenerdigen Sitzreihen": "",
      "Anzahl Sitzplätze": "280",
      "Bestuhlung fix": "Nein",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-G-201.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/G-201/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KOL-G-201/app-files/"],
    availableNow: false,
    nextAvailableSlot: "08:00 tomorrow",
  },
  {
    id: "kol-h-312",
    name: "KOL-H-312 Seminarraum",
    shortCode: "KOL-H-312",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 105,
    description: "A seminar room in the Hauptgebäude (KOL) on the UZH Zentrum campus, suited to smaller classes, workshops and committee meetings.",
    features: ["Wheelchair accessible", "Flexible seating"],
    image: "/images/rooms/kol-h-312/1.jpg",
    imageAlt: "KOL-H-312 Seminarraum: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: false,
      doorWidthCm: 120,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Ja",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "120",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Nein",
      "Trittkantenmarkierungen innerhalb vorhanden": "",
      "Beschreibung der ebenerdigen Sitzreihen": "",
      "Anzahl Sitzplätze": "105",
      "Bestuhlung fix": "Nein",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "68",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "123",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "45",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Classroom", "Boardroom"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-H-312.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/H-312A/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312vorne/app-files/", "https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312hinten/app-files/", "https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312seitengang/app-files/"],
    availableNow: true,
    nextAvailableSlot: "16:00",
  },
  {
    id: "ko2-f-180",
    name: "KO2-F-180 Hörsaal",
    shortCode: "KO2-F-180",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 371,
    description: "A 371-seat lecture hall in the Hauptgebäude (KO2) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/ko2-f-180/1.jpg",
    imageAlt: "KO2-F-180 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 110,
      reservedWheelchairSeats: 2,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "110",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Anzahl Sitzplätze": "371",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "71",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "76",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "24",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "2",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "In der zweiten Reihe rechts und links.",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "1",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "In der dritten Reihe rechts.",
      "Diese Tische sind verschiebbar": "Ja",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "83",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "48",
      "Stromanschluss bei diesen Tischen vorhanden": "Ja",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KO2-F-180.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/KO2/rooms/F-180A/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KO2-F-180/KO2_F_180_hinten/app-files", "https://del.uzh.ch/static/rooms/KO2-F-180/KO2_F_180_vorne/app-files/"],
    availableNow: false,
    nextAvailableSlot: "09:00 tomorrow",
  },
  {
    id: "obere-mensa",
    name: "Restaurant UniTurm / Mensa oben",
    shortCode: "Restaurant UniTurm / Mensa oben",
    building: "Zentrum",
    address: "Rämistrasse 71, 8006 Zürich",
    capacity: 150,
    description: "UZH's upper dining hall and restaurant in the Hauptgebäude (KOL), bookable for receptions and catered events outside regular meal service.",
    features: ["Wheelchair accessible", "Catering on site"],
    image: "/images/rooms/obere-mensa/1.jpg",
    imageAlt: "A university dining hall with long tables and pendant lighting",
    imageCredit: "Diliff (Wikimedia Commons, CC BY-SA)",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Flexible", "Standing"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_obere-mensa.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaAussenbereich/app-files/", "https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaView1/app-files/", "https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaView2/app-files/"],
    availableNow: true,
    nextAvailableSlot: "11:00",
  },
  {
    id: "kum-e-01-02-03",
    name: "KUM-E-01/02/03 Sitzungszimmer",
    shortCode: "KUM-E-01/02/03",
    building: "Zentrum",
    address: "Künstlergasse 15, 8001 Zürich",
    capacity: 30,
    description: "Combinable meeting rooms in Stockargut (KUM), flexible for small seminars, committee meetings and workshops.",
    features: ["Wheelchair accessible", "Combinable rooms", "Movable partitions"],
    image: "/images/rooms/kum-sitzungszimmer.jpg",
    imageAlt: "Modern meeting room with chairs arranged around a table",
    imageCredit: "Unsplash / Wikimedia Commons",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Boardroom", "Classroom", "Flexible"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KUM-E-01_02_03.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/KUM/KUM-E-01/app-files/", "https://del.uzh.ch/static/rooms/KUM/KUM-E-02/app-files/", "https://del.uzh.ch/static/rooms/KUM/KUM-E-03/app-files/"],
    availableNow: false,
    nextAvailableSlot: "13:00 tomorrow",
  },
  {
    id: "raa-lichthof",
    name: "RAA Lichthof",
    shortCode: "RAA Lichthof",
    building: "Zentrum",
    address: "Rämistrasse 59, 8001 Zürich",
    capacity: 200,
    description: "A glass-roofed atrium in Rämistrasse 59 (RAA) — a landmark space for receptions, exhibitions and large gatherings.",
    features: ["Wheelchair accessible", "Historical architecture", "Large event space"],
    image: "/images/rooms/raa-lichthof/1.jpg",
    imageAlt: "A glass-roofed atrium with natural light",
    imageCredit: "Wikimedia Commons, CC BY-SA",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Standing", "Flexible"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_RAA-lichthof.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/RAA-Eingang/RAA_Eingang/app-files/", "https://del.uzh.ch/static/rooms/RAA-Eingang/Raa_Eingang2/app-files/"],
    availableNow: true,
    nextAvailableSlot: "10:00",
  },
  {
    id: "raa-g-01",
    name: "RAA-G-01 Kleine Aula",
    shortCode: "RAA-G-01",
    building: "Zentrum",
    address: "Rämistrasse 59, 8001 Zürich",
    capacity: 102,
    description: "UZH's ceremonial Aula in Rämistrasse 59 (RAA) — a stately hall traditionally used for graduations and formal university ceremonies.",
    features: ["Wheelchair accessible", "Grand acoustics", "Historic hall"],
    image: "/images/rooms/raa-g-01/1.jpg",
    imageAlt: "RAA-G-01 Kleine Aula: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: false,
      doorWidthCm: 172,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "172",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Nein",
      "Trittkantenmarkierungen innerhalb vorhanden": "",
      "Anzahl Sitzplätze": "102",
      "Bestuhlung fix": "Nein",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_RAA-G-01.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/RAA/rooms/G-01/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Hinten/app-files/", "https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Hinten/app-files", "https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Vorne/app-files/", "https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Vorne/app-files"],
    availableNow: true,
    nextAvailableSlot: "15:00",
  },
  {
    id: "y04-g-30",
    name: "Y04-G-30 Hörsaal",
    shortCode: "Y04-G-30",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 577,
    description: "A 577-seat lecture hall in building Y04 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/y04-g-30/1.jpg",
    imageAlt: "Y04-G-30 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 116,
      reservedWheelchairSeats: 3,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "116",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Ja",
      "Anzahl Sitzplätze": "577",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "57",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "32",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "3",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y04-G-30.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y04/rooms/G-30/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y04-G-30/Y04-G-30_vorne/app-files/"],
    availableNow: false,
    nextAvailableSlot: "08:00 tomorrow",
  },
  {
    id: "y15-g-20",
    name: "Y15-G-20 Hörsaal",
    shortCode: "Y15-G-20",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 284,
    description: "A 284-seat lecture hall in building Y15 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/y15-g-20/1.jpg",
    imageAlt: "Y15-G-20 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 112,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "112",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Ja",
      "Beschreibung der ebenerdigen Sitzreihen": "Letzte Reihe.",
      "Anzahl Sitzplätze": "284",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "60",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "35",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y15-G-20.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y15/rooms/G-20/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y15-G-20/Y15-G-20_hinten/app-files", "https://del.uzh.ch/static/rooms/Y15-G-20/Y15-G-20_vorne/app-files"],
    availableNow: true,
    nextAvailableSlot: "16:00",
  },
  {
    id: "y15-g-40",
    name: "Y15-G-40 Hörsaal",
    shortCode: "Y15-G-40",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 284,
    description: "A 284-seat lecture hall in building Y15 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/y15-g-40/1.jpg",
    imageAlt: "Y15-G-40 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 112,
      reservedWheelchairSeats: 1,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "112",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Ja",
      "Anzahl Sitzplätze": "284",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "60",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "35",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "1",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y15-G-40.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y15/rooms/G-40/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y15-G-40/Y15-G-40_hinten/app-files/", "https://del.uzh.ch/static/rooms/Y15-G-40/Y15-G-40_vorne/app-files/"],
    availableNow: false,
    nextAvailableSlot: "09:00 tomorrow",
  },
  {
    id: "y24-g-45",
    name: "Y24-G-45 Hörsaal",
    shortCode: "Y24-G-45",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 446,
    description: "A 446-seat lecture hall in building Y24 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Hearing loop", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/y24-g-45/1.jpg",
    imageAlt: "Y24-G-45 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: true,
      stepsInsideRoom: true,
      doorWidthCm: 84,
      reservedWheelchairSeats: 2,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "84",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Beschreibung der ebenerdigen Sitzreihen": "Die erste und die letzte Sitzreihe.",
      "Anzahl Sitzplätze": "446",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Ja",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "82",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "38",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "2",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "0",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-G-45.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y24/rooms/G-45/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y24-G-45/Y24-G-45_vorne/app-files", "https://del.uzh.ch/static/rooms/Y24-G-45/Y24-G-45_hinten/app-files"],
    availableNow: true,
    nextAvailableSlot: "11:00",
  },
  {
    id: "y21-f-65",
    name: "Y21-F-65 Theatersaal und Seitenraum",
    shortCode: "Y21-F-65",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 222,
    description: "A theatre-style hall with an adjoining side room in building Y21, suited to performances, panel discussions and larger lectures.",
    features: ["Wheelchair accessible", "Stage & side room"],
    image: "/images/rooms/y21-f-65/1.jpg",
    imageAlt: "Y21-F-65 Theatersaal und Seitenraum: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: true,
      doorWidthCm: 88,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "88",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Beschreibung der ebenerdigen Sitzreihen": "Alle Sitzreihen ebenerdig.",
      "Anzahl Sitzplätze": "222",
      "Bestuhlung fix": "Nein",
      "Verstärker-Anlage vorhanden": "Nein",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "",
      "Standort dieser Tische/Pulte in Richtung Wandtafel gesehen": "",
      "Diese Tische sind verschiebbar": "",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "",
      "Stromanschluss bei diesen Tischen vorhanden": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: false,
      videoConferencing: true,
      naturalLight: false,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y21-F-65.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y21/rooms/F-65/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65-Buehne/app-files/", "https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65-Mitte/app-files/", "https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65_Aperoflaeche/app-files/"],
    availableNow: false,
    nextAvailableSlot: "13:00 tomorrow",
  },
  {
    id: "y24-lichthof",
    name: "Y24-G-100 Lichthof",
    shortCode: "Y24-G-100",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 50,
    description: "A glass-roofed atrium in building Y24 — a landmark space for receptions, exhibitions and large gatherings.",
    features: ["Wheelchair accessible", "Historical architecture", "Large event space"],
    image: "/images/rooms/y24-lichthof/1.jpg",
    imageAlt: "Y24-G-100 Lichthof: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: false,
    },
    accessibilityDetails: {
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Standing", "Flexible"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-lichthof.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/Y24/rooms/G-100/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Lichthof_Irchel/Seitentreppe/app-files/", "https://del.uzh.ch/static/rooms/Lichthof_Irchel/Unten/app-files/", "https://del.uzh.ch/static/rooms/Lichthof_Irchel/oben/app-files/"],
    availableNow: true,
    nextAvailableSlot: "10:00",
  },
  {
    id: "y24-galerie",
    name: "Y24 Lichthof Galerie",
    shortCode: "Y24 Lichthof Galerie",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 100,
    description: "An elevated gallery corridor overlooking the atrium in building Y24, suited to exhibitions and informal gatherings.",
    features: ["Wheelchair accessible", "Overlooks atrium"],
    image: "/images/rooms/y24-galerie/1.jpg",
    imageAlt: "An elevated interior gallery corridor overlooking an atrium",
    imageCredit: "Wikimedia Commons, CC BY-SA",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Standing", "Flexible"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-galerie.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y-24-Gallerie/app-files/", "https://del.uzh.ch/static/rooms/Lichthof_Irchel/Oben_Gallerie/app-files/"],
    availableNow: true,
    nextAvailableSlot: "15:00",
  },
  {
    id: "y24-medizinerhof",
    name: "Y24 Medizinerhof Innenhof",
    shortCode: "Y24 Medizinerhof Innenhof",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 200,
    description: "An open-air courtyard at building Y24, suited to outdoor receptions and warm-weather events.",
    features: ["Wheelchair accessible", "Outdoor courtyard"],
    image: "/images/rooms/y24-medizinerhof/1.jpg",
    imageAlt: "An open university courtyard framed by building wings",
    imageCredit: "Wikimedia Commons, CC BY-SA",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Standing"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-medizinerhof.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich1/app-files/", "https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich1/app-files", "https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich2/app-files/"],
    availableNow: false,
    nextAvailableSlot: "08:00 tomorrow",
  },
  {
    id: "green-kitchen-lab",
    name: "Green Kitchen Lab",
    shortCode: "Green Kitchen Lab",
    building: "Irchel",
    address: "Winterthurerstrasse 190, 8057 Zürich",
    capacity: 20,
    description: "A teaching kitchen and lab space on the UZH Irchel campus, suited to hands-on workshops and demo-style events.",
    features: ["Wheelchair accessible", "Teaching kitchen"],
    image: "/images/rooms/green-kitchen-lab/1.jpg",
    imageAlt: "A teaching kitchen classroom with workstations",
    imageCredit: "Wikimedia Commons / DPLA",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Flexible"],
      projector: true,
      whiteboard: true,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_green-kitchen-lab.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-4/app-files/", "https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-3/app-files/", "https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-Aussen/app-files/", "https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-2/app-files/", "https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-1/app-files/"],
    availableNow: true,
    nextAvailableSlot: "16:00",
  },
  {
    id: "bin-0-k-02",
    name: "BIN-0-K.02 Hörsaal",
    shortCode: "BIN-0-K.02",
    building: "Oerlikon",
    address: "Binzmühlestrasse 14, 8050 Zürich",
    capacity: 150,
    description: "A 150-seat lecture hall in the Binzmühle (BIN) on the UZH Oerlikon campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/bin-0-k-02/1.jpg",
    imageAlt: "BIN-0-K.02 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: true,
      doorWidthCm: 86.3,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "86.3",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Anzahl Sitzplätze": "150",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72.6",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "24",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "56",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "1",
      "Diese Tische sind verschiebbar": "Ja",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "83.7",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "47.8",
      "Stromanschluss bei diesen Tischen vorhanden": "Ja",
      "Spezielle Bemerkungen": "",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-K-02.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/BIN/rooms/0-K.02/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_hinten/app-files/", "https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_vorne/app-files", "https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_vorne/app-files/"],
    availableNow: false,
    nextAvailableSlot: "09:00 tomorrow",
  },
  {
    id: "bin-0-k-1",
    name: "BIN-0-K.11/12 Seminarraum",
    shortCode: "BIN-0-K.11/12",
    building: "Oerlikon",
    address: "Binzmühlestrasse 14, 8050 Zürich",
    capacity: 40,
    description: "A seminar room in the Binzmühle (BIN) on the UZH Oerlikon campus, suited to smaller classes, workshops and committee meetings.",
    features: ["Wheelchair accessible", "Flexible seating"],
    image: "/images/rooms/kum-sitzungszimmer.jpg",
    imageAlt: "Modern meeting room with chairs arranged around a table",
    imageCredit: "Unsplash / Wikimedia Commons",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Classroom", "Boardroom"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-K-1.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/BIN-0-K-11/app-files/"],
    availableNow: true,
    nextAvailableSlot: "11:00",
  },
  {
    id: "bin-0-mall",
    name: "BIN Mall",
    shortCode: "BIN Mall",
    building: "Oerlikon",
    address: "Binzmühlestrasse 14, 8050 Zürich",
    capacity: 300,
    description: "The central concourse of the Binzmühle (BIN) — a high-traffic, open space suited to fairs, exhibitions and info days.",
    features: ["Wheelchair accessible", "High-traffic concourse"],
    image: "/images/rooms/bin-0-mall/1.jpg",
    imageAlt: "A bright atrium concourse with skylights",
    imageCredit: "Wikimedia Commons, CC BY-SA",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      notes: "Detailed accessibility data for this space isn't published on Uniability — contact Raumdisposition to confirm before your event.",
    },
    accessibilityDetails: undefined,
    amenities: {
      seatingStyle: ["Standing", "Flexible"],
      projector: false,
      whiteboard: false,
      videoConferencing: false,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-Mall.html",
    uniabilityUrl: undefined,
    visual3dUrls: ["https://del.uzh.ch/static/rooms/BIN-Mall/app-files/"],
    availableNow: false,
    nextAvailableSlot: "13:00 tomorrow",
  },
  {
    id: "bin-1-b-01",
    name: "BIN-1-B.01 Hörsaal",
    shortCode: "BIN-1-B.01",
    building: "Oerlikon",
    address: "Binzmühlestrasse 14, 8050 Zürich",
    capacity: 170,
    description: "A 170-seat lecture hall in the Binzmühle (BIN) on the UZH Oerlikon campus — well suited to lectures, symposia and mid-sized conferences.",
    features: ["Wheelchair accessible", "Tiered seating", "Lecture capture"],
    image: "/images/rooms/bin-1-b-01/1.jpg",
    imageAlt: "BIN-1-B.01 Hörsaal: room view",
    imageCredit: "Uniability UZH",
    accessibility: {
      wheelchairAccessible: true,
      hearingLoop: false,
      stepsInsideRoom: true,
      doorWidthCm: 85,
      reservedWheelchairSeats: 0,
    },
    accessibilityDetails: {
      "Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift": "Nein",
      "Bodenmarkierungen (Leitlinien) zum Raum vorhanden": "Nein",
      "Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden": "Ja",
      "Breite der Türe (in cm)": "85",
      "Höhe der Schwelle beim Eingang (in cm)": "0",
      "Stufen innerhalb des Raumes": "Ja",
      "Trittkantenmarkierungen innerhalb vorhanden": "Nein",
      "Anzahl Sitzplätze": "170",
      "Bestuhlung fix": "Ja",
      "Verstärker-Anlage vorhanden": "Ja",
      "Induktive Höranlage vorhanden": "Nein",
      "Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)": "72.5",
      "Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "56",
      "Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)": "23",
      "Anzahl dieser reservierten, normalen Tische/Plätze": "0",
      "Standort dieser Tische/Plätze in Richtung Wandtafel gesehen": "",
      "Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte": "2",
      "Diese Tische sind verschiebbar": "Ja",
      "Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)": "83",
      "Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)": "43",
      "Stromanschluss bei diesen Tischen vorhanden": "Ja",
    },
    amenities: {
      seatingStyle: ["Theatre"],
      projector: true,
      whiteboard: true,
      videoConferencing: true,
      naturalLight: true,
    },
    sourceUrl: "https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-1-B-01.html",
    uniabilityUrl: "https://www.uniability.uzh.ch/static/current/buildings/BIN/rooms/1-B.01/",
    visual3dUrls: ["https://del.uzh.ch/static/rooms/BIN-1-01/BIN-1-01_hinten/app-files/", "https://del.uzh.ch/static/rooms/BIN-1-01/BIN-1-01_vorne/app-files/"],
    availableNow: true,
    nextAvailableSlot: "10:00",
  },
];

export function capacityBucket(capacity: number): "lt50" | "mid" | "gt100" {
  if (capacity < 50) return "lt50";
  if (capacity <= 100) return "mid";
  return "gt100";
}
