-- Auto-generated by scripts/generate-room-seed.ts — do not hand-edit.
-- Regenerate with: npx tsx scripts/generate-room-seed.ts > supabase/migrations/20260916000006_seed_rooms.sql

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'hah-e-03', 'HAH-E-03 Hörsaal', 'HAH-E-03',
  (select id from buildings where code = 'HAH'),
  (select id from room_types where slug = 'hoersaal'),
  442, 'A 442-seat lecture hall in Häldeliweg (HAH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/hah-e-03/1.jpg', 'HAH-E-03 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-03.html', 'https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-03/', '{"https://del.uzh.ch/static/rooms//HAH-E-03/HAH-E-03_vorne/app-files","https://del.uzh.ch/static/rooms/HAH-E-03/HAH-E-03_hinten/app-files"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 95.4, 2, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"95.4","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Anzahl Sitzplätze":"442","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72.8","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"102","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"28","Anzahl dieser reservierten, normalen Tische/Plätze":"2","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'hah-e-10', 'HAH-E-10 Seminarraum', 'HAH-E-10',
  (select id from buildings where code = 'HAH'),
  (select id from room_types where slug = 'seminarraum'),
  36, 'A seminar room in Häldeliweg (HAH) on the UZH Zentrum campus, suited to smaller classes, workshops and committee meetings.', '{"Wheelchair accessible","Flexible seating"}',
  '/images/rooms/hah-e-10/1.jpg', 'HAH-E-10 Seminarraum: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-10.html', 'https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-10/', '{"https://del.uzh.ch/static/rooms/HAH-E-10/app-files","https://del.uzh.ch/static/rooms/HAH-E-10/app-files/"}',
  '{"Classroom","Boardroom"}', true, true, true, true,
  true, false, false, 102, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"102","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Nein","Trittkantenmarkierungen innerhalb vorhanden":"","Anzahl Sitzplätze":"36","Bestuhlung fix":"Nein","Standorte der von Studierenden benutzbaren Stromanschlüsse":"keine vorhanden","Verstärker-Anlage vorhanden":"Nein","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"67.2","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"65","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"55","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":"","Spezielle Bemerkungen":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'hah-e-11', 'HAH-E-11 Hörsaal', 'HAH-E-11',
  (select id from buildings where code = 'HAH'),
  (select id from room_types where slug = 'hoersaal'),
  285, 'A 285-seat lecture hall in Häldeliweg (HAH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/hah-e-11/1.jpg', 'HAH-E-11 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_HAH-E-11.html', 'https://www.uniability.uzh.ch/static/current/buildings/HAH/rooms/E-11/', '{"https://del.uzh.ch/static/rooms//HAH-E-03/HAH-E-03_vorne/app-files","https://del.uzh.ch/static/rooms/Hah-E-11/HAH-E-11_vorne/app-files","https://del.uzh.ch/static/rooms/Hah-E-11/HAH-E-11_hinten/app-files"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 92, 2, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"92","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Anzahl Sitzplätze":"285","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"73.1","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"58.9","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"16","Anzahl dieser reservierten, normalen Tische/Plätze":"2","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'koh-b-10', 'KOH-B-10 Hörsaal', 'KOH-B-10',
  (select id from buildings where code = 'KOH'),
  (select id from room_types where slug = 'hoersaal'),
  463, 'A 463-seat lecture hall in the Hauptgebäude (KOH) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/koh-b-10/1.jpg', 'KOH-B-10 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOH-B-10.html', 'https://www.uniability.uzh.ch/static/current/buildings/KOH/rooms/B-10/', '{"https://del.uzh.ch/static/rooms/KOH-B-10/KOH-B-10vorne/app-files/","https://del.uzh.ch/static/rooms/KOH-B-10/KOH-B-10hinten/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 115, 2, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"115","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Ja","Anzahl Sitzplätze":"463","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"74","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"66","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"34","Anzahl dieser reservierten, normalen Tische/Plätze":"2","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'kol-lichthof', 'KOL Lichthof', 'KOL Lichthof',
  (select id from buildings where code = 'KOL'),
  (select id from room_types where slug = 'lichthof'),
  500, 'A glass-roofed atrium in the Hauptgebäude (KOL) — a landmark space for receptions, exhibitions and large gatherings.', '{"Wheelchair accessible","Historical architecture","Large event space"}',
  '/images/rooms/kol-lichthof.jpg', 'The historic glass-roofed Lichthof atrium at UZH''s main building', 'Campus Culture UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-lichthof.html', null, '{"https://del.uzh.ch/static/rooms/Lichthof-UZH-Zentrum/LichthofNord/app-files/","https://del.uzh.ch/static/rooms/Lichthof-UZH-Zentrum/LichthofSued/app-files/"}',
  '{"Standing","Flexible"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'kol-f-101', 'KOL-F-101 Hörsaal', 'KOL-F-101',
  (select id from buildings where code = 'KOL'),
  (select id from room_types where slug = 'hoersaal'),
  213, 'A 213-seat lecture hall in the Hauptgebäude (KOL) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/kol-f-101/1.jpg', 'KOL-F-101 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-F-101.html', 'https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/F-101/', '{"https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_hinten/app-files/","https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_vornemitte/app-files/","https://del.uzh.ch/static/rooms/KOL-F-101/KOL-F-101_vornelinks/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 102, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Ja","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"102","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Beschreibung der ebenerdigen Sitzreihen":"Die ersten vier Reihen sind ebenerdig.","Anzahl Sitzplätze":"213","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"73","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"56","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"32","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"2","Diese Tische sind verschiebbar":"Ja","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"84","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"45","Stromanschluss bei diesen Tischen vorhanden":"Ja"}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'kol-g-201', 'KOL-G-201 Aula', 'KOL-G-201',
  (select id from buildings where code = 'KOL'),
  (select id from room_types where slug = 'aula'),
  280, 'UZH''s ceremonial Aula in the Hauptgebäude (KOL) — a stately hall traditionally used for graduations and formal university ceremonies.', '{"Wheelchair accessible","Hearing loop","Grand acoustics","Historic hall"}',
  '/images/rooms/kol-g-201/1.jpg', 'KOL-G-201 Aula: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-G-201.html', 'https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/G-201/', '{"https://del.uzh.ch/static/rooms/KOL-G-201/app-files/"}',
  '{"Theatre"}', true, false, false, true,
  true, true, false, 120, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Ja","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"120","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Nein","Trittkantenmarkierungen innerhalb vorhanden":"","Beschreibung der ebenerdigen Sitzreihen":"","Anzahl Sitzplätze":"280","Bestuhlung fix":"Nein","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'kol-h-312', 'KOL-H-312 Seminarraum', 'KOL-H-312',
  (select id from buildings where code = 'KOL'),
  (select id from room_types where slug = 'seminarraum'),
  105, 'A seminar room in the Hauptgebäude (KOL) on the UZH Zentrum campus, suited to smaller classes, workshops and committee meetings.', '{"Wheelchair accessible","Flexible seating"}',
  '/images/rooms/kol-h-312/1.jpg', 'KOL-H-312 Seminarraum: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KOL-H-312.html', 'https://www.uniability.uzh.ch/static/current/buildings/KOL/rooms/H-312A/', '{"https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312vorne/app-files/","https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312hinten/app-files/","https://del.uzh.ch/static/rooms/KOL-H-312/KOL-H-312seitengang/app-files/"}',
  '{"Classroom","Boardroom"}', true, true, true, true,
  true, false, false, 120, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Ja","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"120","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Nein","Trittkantenmarkierungen innerhalb vorhanden":"","Beschreibung der ebenerdigen Sitzreihen":"","Anzahl Sitzplätze":"105","Bestuhlung fix":"Nein","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"68","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"123","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"45","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'ko2-f-180', 'KO2-F-180 Hörsaal', 'KO2-F-180',
  (select id from buildings where code = 'KO2'),
  (select id from room_types where slug = 'hoersaal'),
  371, 'A 371-seat lecture hall in the Hauptgebäude (KO2) on the UZH Zentrum campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/ko2-f-180/1.jpg', 'KO2-F-180 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KO2-F-180.html', 'https://www.uniability.uzh.ch/static/current/buildings/KO2/rooms/F-180A/', '{"https://del.uzh.ch/static/rooms/KO2-F-180/KO2_F_180_hinten/app-files","https://del.uzh.ch/static/rooms/KO2-F-180/KO2_F_180_vorne/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 110, 2, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"110","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Anzahl Sitzplätze":"371","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"71","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"76","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"24","Anzahl dieser reservierten, normalen Tische/Plätze":"2","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"In der zweiten Reihe rechts und links.","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"1","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"In der dritten Reihe rechts.","Diese Tische sind verschiebbar":"Ja","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"83","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"48","Stromanschluss bei diesen Tischen vorhanden":"Ja"}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'obere-mensa', 'Restaurant UniTurm / Mensa oben', 'Restaurant UniTurm / Mensa oben',
  (select id from buildings where code = 'KOL'),
  (select id from room_types where slug = 'mensa'),
  150, 'UZH''s upper dining hall and restaurant in the Hauptgebäude (KOL), bookable for receptions and catered events outside regular meal service.', '{"Wheelchair accessible","Catering on site"}',
  '/images/rooms/obere-mensa/1.jpg', 'A university dining hall with long tables and pendant lighting', 'Diliff (Wikimedia Commons, CC BY-SA)', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_obere-mensa.html', null, '{"https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaAussenbereich/app-files/","https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaView1/app-files/","https://del.uzh.ch/static/rooms/obere-Mensa/ObereMensaView2/app-files/"}',
  '{"Flexible","Standing"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'kum-e-01-02-03', 'KUM-E-01/02/03 Sitzungszimmer', 'KUM-E-01/02/03',
  (select id from buildings where code = 'KUM'),
  (select id from room_types where slug = 'sitzungszimmer'),
  30, 'Combinable meeting rooms in Stockargut (KUM), flexible for small seminars, committee meetings and workshops.', '{"Wheelchair accessible","Combinable rooms","Movable partitions"}',
  '/images/rooms/kum-sitzungszimmer.jpg', 'Modern meeting room with chairs arranged around a table', 'Unsplash / Wikimedia Commons', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_KUM-E-01_02_03.html', null, '{"https://del.uzh.ch/static/rooms/KUM/KUM-E-01/app-files/","https://del.uzh.ch/static/rooms/KUM/KUM-E-02/app-files/","https://del.uzh.ch/static/rooms/KUM/KUM-E-03/app-files/"}',
  '{"Boardroom","Classroom","Flexible"}', true, true, true, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'raa-lichthof', 'RAA Lichthof', 'RAA Lichthof',
  (select id from buildings where code = 'RAA'),
  (select id from room_types where slug = 'lichthof'),
  200, 'A glass-roofed atrium in Rämistrasse 59 (RAA) — a landmark space for receptions, exhibitions and large gatherings.', '{"Wheelchair accessible","Historical architecture","Large event space"}',
  '/images/rooms/raa-lichthof/1.jpg', 'A glass-roofed atrium with natural light', 'Wikimedia Commons, CC BY-SA', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_RAA-lichthof.html', null, '{"https://del.uzh.ch/static/rooms/RAA-Eingang/RAA_Eingang/app-files/","https://del.uzh.ch/static/rooms/RAA-Eingang/Raa_Eingang2/app-files/"}',
  '{"Standing","Flexible"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'raa-g-01', 'RAA-G-01 Kleine Aula', 'RAA-G-01',
  (select id from buildings where code = 'RAA'),
  (select id from room_types where slug = 'aula'),
  102, 'UZH''s ceremonial Aula in Rämistrasse 59 (RAA) — a stately hall traditionally used for graduations and formal university ceremonies.', '{"Wheelchair accessible","Grand acoustics","Historic hall"}',
  '/images/rooms/raa-g-01/1.jpg', 'RAA-G-01 Kleine Aula: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_RAA-G-01.html', 'https://www.uniability.uzh.ch/static/current/buildings/RAA/rooms/G-01/', '{"https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Hinten/app-files/","https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Hinten/app-files","https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Vorne/app-files/","https://del.uzh.ch/static/rooms/RAA-G-01/RAA-G-01-Vorne/app-files"}',
  '{"Theatre"}', true, false, false, true,
  true, false, false, 172, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"172","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Nein","Trittkantenmarkierungen innerhalb vorhanden":"","Anzahl Sitzplätze":"102","Bestuhlung fix":"Nein","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y04-g-30', 'Y04-G-30 Hörsaal', 'Y04-G-30',
  (select id from buildings where code = 'Y04'),
  (select id from room_types where slug = 'hoersaal'),
  577, 'A 577-seat lecture hall in building Y04 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/y04-g-30/1.jpg', 'Y04-G-30 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y04-G-30.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y04/rooms/G-30/', '{"https://del.uzh.ch/static/rooms/Y04-G-30/Y04-G-30_vorne/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 116, 3, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"116","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Ja","Anzahl Sitzplätze":"577","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"57","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"32","Anzahl dieser reservierten, normalen Tische/Plätze":"3","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":"","Spezielle Bemerkungen":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y15-g-20', 'Y15-G-20 Hörsaal', 'Y15-G-20',
  (select id from buildings where code = 'Y15'),
  (select id from room_types where slug = 'hoersaal'),
  284, 'A 284-seat lecture hall in building Y15 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/y15-g-20/1.jpg', 'Y15-G-20 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y15-G-20.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y15/rooms/G-20/', '{"https://del.uzh.ch/static/rooms/Y15-G-20/Y15-G-20_hinten/app-files","https://del.uzh.ch/static/rooms/Y15-G-20/Y15-G-20_vorne/app-files"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 112, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"112","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Ja","Beschreibung der ebenerdigen Sitzreihen":"Letzte Reihe.","Anzahl Sitzplätze":"284","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"60","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"35","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":"","Spezielle Bemerkungen":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y15-g-40', 'Y15-G-40 Hörsaal', 'Y15-G-40',
  (select id from buildings where code = 'Y15'),
  (select id from room_types where slug = 'hoersaal'),
  284, 'A 284-seat lecture hall in building Y15 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/y15-g-40/1.jpg', 'Y15-G-40 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y15-G-40.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y15/rooms/G-40/', '{"https://del.uzh.ch/static/rooms/Y15-G-40/Y15-G-40_hinten/app-files/","https://del.uzh.ch/static/rooms/Y15-G-40/Y15-G-40_vorne/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 112, 1, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"112","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Ja","Anzahl Sitzplätze":"284","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"60","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"35","Anzahl dieser reservierten, normalen Tische/Plätze":"1","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":"","Spezielle Bemerkungen":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y24-g-45', 'Y24-G-45 Hörsaal', 'Y24-G-45',
  (select id from buildings where code = 'Y24'),
  (select id from room_types where slug = 'hoersaal'),
  446, 'A 446-seat lecture hall in building Y24 on the UZH Irchel campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Hearing loop","Tiered seating","Lecture capture"}',
  '/images/rooms/y24-g-45/1.jpg', 'Y24-G-45 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-G-45.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y24/rooms/G-45/', '{"https://del.uzh.ch/static/rooms/Y24-G-45/Y24-G-45_vorne/app-files","https://del.uzh.ch/static/rooms/Y24-G-45/Y24-G-45_hinten/app-files"}',
  '{"Theatre"}', true, true, true, true,
  true, true, true, 84, 2, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"84","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Beschreibung der ebenerdigen Sitzreihen":"Die erste und die letzte Sitzreihe.","Anzahl Sitzplätze":"446","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Ja","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"82","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"38","Anzahl dieser reservierten, normalen Tische/Plätze":"2","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"0","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y21-f-65', 'Y21-F-65 Theatersaal und Seitenraum', 'Y21-F-65',
  (select id from buildings where code = 'Y21'),
  (select id from room_types where slug = 'theatersaal'),
  222, 'A theatre-style hall with an adjoining side room in building Y21, suited to performances, panel discussions and larger lectures.', '{"Wheelchair accessible","Stage & side room"}',
  '/images/rooms/y21-f-65/1.jpg', 'Y21-F-65 Theatersaal und Seitenraum: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y21-F-65.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y21/rooms/F-65/', '{"https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65-Buehne/app-files/","https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65-Mitte/app-files/","https://del.uzh.ch/static/rooms/Y21-F-65/Y21-F-65_Aperoflaeche/app-files/"}',
  '{"Theatre"}', true, false, true, false,
  true, false, true, 88, null, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"88","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Beschreibung der ebenerdigen Sitzreihen":"Alle Sitzreihen ebenerdig.","Anzahl Sitzplätze":"222","Bestuhlung fix":"Nein","Verstärker-Anlage vorhanden":"Nein","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"","Anzahl dieser reservierten, normalen Tische/Plätze":"","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"","Standort dieser Tische/Pulte in Richtung Wandtafel gesehen":"","Diese Tische sind verschiebbar":"","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"","Stromanschluss bei diesen Tischen vorhanden":""}'::jsonb, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y24-lichthof', 'Y24-G-100 Lichthof', 'Y24-G-100',
  (select id from buildings where code = 'Y24'),
  (select id from room_types where slug = 'lichthof'),
  50, 'A glass-roofed atrium in building Y24 — a landmark space for receptions, exhibitions and large gatherings.', '{"Wheelchair accessible","Historical architecture","Large event space"}',
  '/images/rooms/y24-lichthof/1.jpg', 'Y24-G-100 Lichthof: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-lichthof.html', 'https://www.uniability.uzh.ch/static/current/buildings/Y24/rooms/G-100/', '{"https://del.uzh.ch/static/rooms/Lichthof_Irchel/Seitentreppe/app-files/","https://del.uzh.ch/static/rooms/Lichthof_Irchel/Unten/app-files/","https://del.uzh.ch/static/rooms/Lichthof_Irchel/oben/app-files/"}',
  '{"Standing","Flexible"}', false, false, false, true,
  true, false, false, null, null, null, '{"Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Spezielle Bemerkungen":""}'::jsonb, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y24-galerie', 'Y24 Lichthof Galerie', 'Y24 Lichthof Galerie',
  (select id from buildings where code = 'Y24'),
  (select id from room_types where slug = 'galerie'),
  100, 'An elevated gallery corridor overlooking the atrium in building Y24, suited to exhibitions and informal gatherings.', '{"Wheelchair accessible","Overlooks atrium"}',
  '/images/rooms/y24-galerie/1.jpg', 'An elevated interior gallery corridor overlooking an atrium', 'Wikimedia Commons, CC BY-SA', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-galerie.html', null, '{"https://del.uzh.ch/static/rooms/Y-24-Gallerie/app-files/","https://del.uzh.ch/static/rooms/Lichthof_Irchel/Oben_Gallerie/app-files/"}',
  '{"Standing","Flexible"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'y24-medizinerhof', 'Y24 Medizinerhof Innenhof', 'Y24 Medizinerhof Innenhof',
  (select id from buildings where code = 'Y24'),
  (select id from room_types where slug = 'innenhof'),
  200, 'An open-air courtyard at building Y24, suited to outdoor receptions and warm-weather events.', '{"Wheelchair accessible","Outdoor courtyard"}',
  '/images/rooms/y24-medizinerhof/1.jpg', 'An open university courtyard framed by building wings', 'Wikimedia Commons, CC BY-SA', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_Y24-medizinerhof.html', null, '{"https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich1/app-files/","https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich1/app-files","https://del.uzh.ch/static/rooms/Y-24-Aussenbereich/Y-24-Aussenbereich2/app-files/"}',
  '{"Standing"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'green-kitchen-lab', 'Green Kitchen Lab', 'Green Kitchen Lab',
  (select id from buildings where code = 'Y24'),
  (select id from room_types where slug = 'kitchen'),
  20, 'A teaching kitchen and lab space on the UZH Irchel campus, suited to hands-on workshops and demo-style events.', '{"Wheelchair accessible","Teaching kitchen"}',
  '/images/rooms/green-kitchen-lab/1.jpg', 'A teaching kitchen classroom with workstations', 'Wikimedia Commons / DPLA', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_green-kitchen-lab.html', null, '{"https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-4/app-files/","https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-3/app-files/","https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-Aussen/app-files/","https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-2/app-files/","https://del.uzh.ch/static/rooms/Green-Kitchen-Lab/Green-Kitchen-Lab-1/app-files/"}',
  '{"Flexible"}', true, true, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'bin-0-k-02', 'BIN-0-K.02 Hörsaal', 'BIN-0-K.02',
  (select id from buildings where code = 'BIN'),
  (select id from room_types where slug = 'hoersaal'),
  150, 'A 150-seat lecture hall in the Binzmühle (BIN) on the UZH Oerlikon campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Tiered seating","Lecture capture"}',
  '/images/rooms/bin-0-k-02/1.jpg', 'BIN-0-K.02 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-K-02.html', 'https://www.uniability.uzh.ch/static/current/buildings/BIN/rooms/0-K.02/', '{"https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_hinten/app-files/","https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_vorne/app-files","https://del.uzh.ch/static/rooms/BIN-0-K-02/BIN-0-K-02_vorne/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, false, true, 86.3, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"86.3","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Anzahl Sitzplätze":"150","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72.6","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"24","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"56","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"1","Diese Tische sind verschiebbar":"Ja","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"83.7","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"47.8","Stromanschluss bei diesen Tischen vorhanden":"Ja","Spezielle Bemerkungen":""}'::jsonb, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'bin-0-k-1', 'BIN-0-K.11/12 Seminarraum', 'BIN-0-K.11/12',
  (select id from buildings where code = 'BIN'),
  (select id from room_types where slug = 'seminarraum'),
  40, 'A seminar room in the Binzmühle (BIN) on the UZH Oerlikon campus, suited to smaller classes, workshops and committee meetings.', '{"Wheelchair accessible","Flexible seating"}',
  '/images/rooms/kum-sitzungszimmer.jpg', 'Modern meeting room with chairs arranged around a table', 'Unsplash / Wikimedia Commons', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-K-1.html', null, '{"https://del.uzh.ch/static/rooms/BIN-0-K-11/app-files/"}',
  '{"Classroom","Boardroom"}', true, true, true, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, false
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'bin-0-mall', 'BIN Mall', 'BIN Mall',
  (select id from buildings where code = 'BIN'),
  (select id from room_types where slug = 'mall'),
  300, 'The central concourse of the Binzmühle (BIN) — a high-traffic, open space suited to fairs, exhibitions and info days.', '{"Wheelchair accessible","High-traffic concourse"}',
  '/images/rooms/bin-0-mall/1.jpg', 'A bright atrium concourse with skylights', 'Wikimedia Commons, CC BY-SA', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-0-Mall.html', null, '{"https://del.uzh.ch/static/rooms/BIN-Mall/app-files/"}',
  '{"Standing","Flexible"}', false, false, false, true,
  true, false, null, null, null, 'Detailed accessibility data for this space isn''t published on Uniability — contact Raumdisposition to confirm before your event.', null, true
);

insert into rooms (
  code, name, short_code, building_id, room_type_id, capacity, description, features,
  image_url, image_alt, image_credit, source_url, uniability_url, visual_3d_urls,
  seating_style, has_projector, has_whiteboard, has_video_conferencing, has_natural_light,
  wheelchair_accessible, hearing_loop, steps_inside_room, door_width_cm, reserved_wheelchair_seats, accessibility_notes, accessibility_details, requires_approval
) values (
  'bin-1-b-01', 'BIN-1-B.01 Hörsaal', 'BIN-1-B.01',
  (select id from buildings where code = 'BIN'),
  (select id from room_types where slug = 'hoersaal'),
  170, 'A 170-seat lecture hall in the Binzmühle (BIN) on the UZH Oerlikon campus — well suited to lectures, symposia and mid-sized conferences.', '{"Wheelchair accessible","Tiered seating","Lecture capture"}',
  '/images/rooms/bin-1-b-01/1.jpg', 'BIN-1-B.01 Hörsaal: room view', 'Uniability UZH', 'https://www.del.uzh.ch/de/campusnutzung-und-bewilligungen/raeume/lehr-und-veranstaltungsraeume/raeumlichkeiten/eventraeume/rauminformation_BIN-1-B-01.html', 'https://www.uniability.uzh.ch/static/current/buildings/BIN/rooms/1-B.01/', '{"https://del.uzh.ch/static/rooms/BIN-1-01/BIN-1-01_hinten/app-files/","https://del.uzh.ch/static/rooms/BIN-1-01/BIN-1-01_vorne/app-files/"}',
  '{"Theatre"}', true, true, true, true,
  true, false, true, 85, 0, null, '{"Raumbezeichnungs-Tafel mit Braille- oder Relief-Schrift":"Nein","Bodenmarkierungen (Leitlinien) zum Raum vorhanden":"Nein","Stufenloser Weg von ausserhalb des Gebäudes bis hierhin vorhanden":"Ja","Breite der Türe (in cm)":"85","Höhe der Schwelle beim Eingang (in cm)":"0","Stufen innerhalb des Raumes":"Ja","Trittkantenmarkierungen innerhalb vorhanden":"Nein","Anzahl Sitzplätze":"170","Bestuhlung fix":"Ja","Verstärker-Anlage vorhanden":"Ja","Induktive Höranlage vorhanden":"Nein","Höhe ab Boden der Unterkante der Tischplatte eines normalen Tisches (in cm)":"72.5","Breite des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"56","Tiefe des befahrbaren Platzes unterhalb eines normalen Tisches (in cm)":"23","Anzahl dieser reservierten, normalen Tische/Plätze":"0","Standort dieser Tische/Plätze in Richtung Wandtafel gesehen":"","Anzahl spezieller, elektrisch höhenverstellbarer Tische/Pulte":"2","Diese Tische sind verschiebbar":"Ja","Breite des befahrbaren Platzes unterhalb eines Pultes (in cm)":"83","Tiefe des befahrbaren Platzes unterhalb eines Pultes (in cm)":"43","Stromanschluss bei diesen Tischen vorhanden":"Ja"}'::jsonb, false
);

